export const signUpUrl = 'https://enbostad.herokuapp.com/users'
export const signInUrl = 'https://enbostad.herokuapp.com/sessions'
export const listUrl = 'https://enbostad.herokuapp.com/list'
export const saveDataUrl = 'https://enbostad.herokuapp.com/saveData'
export const getDataUrl = 'https://enbostad.herokuapp.com/getData'
